### ISSUE TITLE
In Part 4, vectorize all of the code without docstrings.

### ISSUE THREAD

**Issue by ZhaoYi1031** [hamelsmu/code_search#43]
I am wondering the reasons why we need to vectorize all of the code **without docstrings**, can we use the code that we have seen by the model?(if we do so, what are the problems) Thanks a lot.

**Comment by hamelsmu** [comment]
It was only to demonstrate that you can find code even if the code doesn't a docstring, because if the code already has a good docstring then you can probably find it using traditional search.  In practice, if we are trying to build a real semantic search system we would definitely find another way (perhaps using a separate encoder) to learn a representation of the docstring as well and have that be considered as well as the code representation.
